version: "3"
services:
    database:
        build: ./mysql 
        ports: 
            - "3306:3306"
        #Habililta autenticación con contraseña desde mysql
        command: --default-authentication-plugin=mysql_native_password 
        #Variables de entorno
        environment:
            MYSQL_DATABASE: feloba
            MYSQL_PASSWORD: 1234
            MYSQL_ROOT_PASSWORD: root
        volumes:
            #sincronización bbdd
            - .:/docker-entrypoint-initdb.d
        networks:
            - default

    web:
        build: ./apache
        ports: 
            - "80:80"
        volumes:
            - .:/var/www/html
        links:
            - database
        networks:
            - default

    adminphp:
        build: ./phpmyadmin
        links: 
            - database
        ports:
            - "8000:80"
        environment:
            MYSQL_USER: fer
            MYSQL_PASSWORD: 1234
            MYSQL_ROOT_PASSWORD: root
